// <auto-generated />
using System;
using DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ForagerDbContext))]
    [Migration("20251207042854_UpDownVotes")]
    partial class UpDownVotes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Models.User", b =>
                {
                    b.Property<Guid>("UsrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UsrBio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsrCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsrEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsrExpScore")
                        .HasColumnType("int");

                    b.Property<int?>("UsrFindsNum")
                        .HasColumnType("int");

                    b.Property<DateTime>("UsrJoinedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UsrName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsrStateorProvince")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsrZipCode")
                        .HasColumnType("int");

                    b.HasKey("UsrId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("DataAccess.Models.UserFind", b =>
                {
                    b.Property<Guid>("UsfId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("UsfAccuracyScore")
                        .HasColumnType("int");

                    b.Property<string>("UsfDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsfDownVotes")
                        .HasColumnType("int");

                    b.Property<string>("UsfFeatures")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UsfFindDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UsfHarvestMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsfLookAlikes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsfName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsfSpeciesName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsfSpeciesType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsfTastesLike")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsfUpVotes")
                        .HasColumnType("int");

                    b.Property<string>("UsfUseCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UsfUsrId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UsfId");

                    b.HasIndex("UsfUsrId");

                    b.ToTable("UserFinds", (string)null);
                });

            modelBuilder.Entity("DataAccess.Models.UserFindLocation", b =>
                {
                    b.Property<Guid>("UslId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("UslLatitude")
                        .HasColumnType("float");

                    b.Property<double>("UslLongitude")
                        .HasColumnType("float");

                    b.Property<Guid>("UslUsfId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UslId");

                    b.HasIndex("UslUsfId")
                        .IsUnique();

                    b.ToTable("UserFindLocation", (string)null);
                });

            modelBuilder.Entity("DataAccess.Models.UserFindsComment", b =>
                {
                    b.Property<Guid>("UscId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UscComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UscCommentDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UscCommentScore")
                        .HasColumnType("int");

                    b.Property<int?>("UscDownVotes")
                        .HasColumnType("int");

                    b.Property<Guid?>("UscParentCommentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("UscUpVotes")
                        .HasColumnType("int");

                    b.HasKey("UscId");

                    b.HasIndex("UscParentCommentId");

                    b.ToTable("UserFindsComments", (string)null);
                });

            modelBuilder.Entity("DataAccess.Models.UserFindsCommentXref", b =>
                {
                    b.Property<Guid>("UcxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UcxUscId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UcxUsfId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UcxUsrId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UcxId");

                    b.HasIndex("UcxUscId")
                        .IsUnique();

                    b.HasIndex("UcxUsfId");

                    b.HasIndex("UcxUsrId");

                    b.ToTable("UserFindsCommentXref", (string)null);
                });

            modelBuilder.Entity("DataAccess.Models.UserImage", b =>
                {
                    b.Property<Guid>("UsiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UsiImageData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UsiUsfId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UsiUsrId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UsiId");

                    b.HasIndex("UsiUsfId");

                    b.HasIndex("UsiUsrId")
                        .IsUnique()
                        .HasFilter("[UsiUsrId] IS NOT NULL");

                    b.ToTable("UserImages", (string)null);
                });

            modelBuilder.Entity("DataAccess.Models.UserMessage", b =>
                {
                    b.Property<Guid>("UsmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserUsrId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UsmMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UsmReceivedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UsmRecipientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UsmSendDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UsmSenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UsmStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UsmSubject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UsmUsrId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UsmId");

                    b.HasIndex("UserUsrId");

                    b.ToTable("UserMessages", (string)null);
                });

            modelBuilder.Entity("DataAccess.Models.UserSecurity", b =>
                {
                    b.Property<Guid>("UssId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UssLastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UssLastLogoffDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UssPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UssUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UssUsrId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UssId");

                    b.HasIndex("UssUsrId")
                        .IsUnique();

                    b.ToTable("UserSecurity", (string)null);
                });

            modelBuilder.Entity("DataAccess.Models.UserFind", b =>
                {
                    b.HasOne("DataAccess.Models.User", "User")
                        .WithMany("UserFinds")
                        .HasForeignKey("UsfUsrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccess.Models.UserFindLocation", b =>
                {
                    b.HasOne("DataAccess.Models.UserFind", "UserFind")
                        .WithOne("UserFindLocation")
                        .HasForeignKey("DataAccess.Models.UserFindLocation", "UslUsfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserFind");
                });

            modelBuilder.Entity("DataAccess.Models.UserFindsComment", b =>
                {
                    b.HasOne("DataAccess.Models.UserFindsComment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("UscParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentComment");
                });

            modelBuilder.Entity("DataAccess.Models.UserFindsCommentXref", b =>
                {
                    b.HasOne("DataAccess.Models.UserFindsComment", "UserFindsComment")
                        .WithOne("UserFindsCommentXref")
                        .HasForeignKey("DataAccess.Models.UserFindsCommentXref", "UcxUscId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Models.UserFind", "UserFind")
                        .WithMany("UserFindsCommentXrefs")
                        .HasForeignKey("UcxUsfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Models.User", "User")
                        .WithMany("UserFindsCommentXrefs")
                        .HasForeignKey("UcxUsrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserFind");

                    b.Navigation("UserFindsComment");
                });

            modelBuilder.Entity("DataAccess.Models.UserImage", b =>
                {
                    b.HasOne("DataAccess.Models.UserFind", "UserFind")
                        .WithMany("UserImages")
                        .HasForeignKey("UsiUsfId");

                    b.HasOne("DataAccess.Models.User", "User")
                        .WithOne("UserImage")
                        .HasForeignKey("DataAccess.Models.UserImage", "UsiUsrId");

                    b.Navigation("User");

                    b.Navigation("UserFind");
                });

            modelBuilder.Entity("DataAccess.Models.UserMessage", b =>
                {
                    b.HasOne("DataAccess.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserUsrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccess.Models.UserSecurity", b =>
                {
                    b.HasOne("DataAccess.Models.User", "User")
                        .WithOne("UserSecurity")
                        .HasForeignKey("DataAccess.Models.UserSecurity", "UssUsrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccess.Models.User", b =>
                {
                    b.Navigation("UserFinds");

                    b.Navigation("UserFindsCommentXrefs");

                    b.Navigation("UserImage")
                        .IsRequired();

                    b.Navigation("UserSecurity")
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccess.Models.UserFind", b =>
                {
                    b.Navigation("UserFindLocation")
                        .IsRequired();

                    b.Navigation("UserFindsCommentXrefs");

                    b.Navigation("UserImages");
                });

            modelBuilder.Entity("DataAccess.Models.UserFindsComment", b =>
                {
                    b.Navigation("Replies");

                    b.Navigation("UserFindsCommentXref")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
